stages:
  - build
#  - docker

build:
  image: apunreddy/gradle:latest
  before_script:
    - chmod +x gradlew
    - docker login -u apunreddy -p A@sand0421 docker.io
  stage: build
  script: ./gradlew clean build jib
#  artifacts:
#    paths:
#      - build/**

#docker:
#  image: docker:latest
#  before_script:
#    - chmod +x gradlew
#  #    - docker login -u apunreddy -p A@sand0421 docker.io
#  stage: build
#  script: ./gradlew clean build
#  artifacts:
#    paths:
#      - build/**

